name: Clang-Tidy CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive
      
      - name: Setup Clang-Tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy --no-install-recommends

      - name: Configure CMake
        run: >
          cmake
          -B build
          -S .
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Link compile_commands.json to root
        run: >
          ln -s build/compile_commands.json .

      - name: Run clang-tidy and annotate
        run: scripts/run-clang-tidy.sh
