name: Formatting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          ./scripts/run-clang-format.sh
          git diff --exit-code
