name: Release

on:
  push:
    tags:
      - "v*"

env:
  LUNARG_VULKAN_SDK_VERSION: 1.4.304.1
  JAVA_TUMERIN_JDK_VERSION: 21
  ANDROID_NDK_VERSION: r27d

jobs:
  release:
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: glfw-linux
            engine-backend: glfw
            operating-system: linux
            runner: ubuntu-latest
            target: xider-desktop-linux
          - name: glfw-macos
            engine-backend: glfw
            operating-system: macos
            runner: macos-latest
            target: xider-desktop-macos
          - name: glfw-windows
            engine-backend: glfw
            operating-system: windows
            runner: windows-latest
            target: xider-desktop-windows
          - name: openxr-linux
            engine-backend: openxr
            operating-system: linux
            runner: ubuntu-latest
            target: xider-xr-linux
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Install Ubuntu dependencies
        if: matrix.runner == 'ubuntu-latest'
        run: bash scripts/install_ubuntu_dependencies.sh

      - name: Configure Vulkan SDK using the downloaded spec
        uses: humbletim/setup-vulkan-sdk@v1.2.1
        with:
          vulkan-query-version: ${{ env.LUNARG_VULKAN_SDK_VERSION }}
          vulkan-components: Vulkan-Headers, Vulkan-Loader
          vulkan-use-cache: true

      - name: Configure CMake
        run: >
          cmake
          -B ${{ github.workspace }}/build
          -S ${{ github.workspace }}
          -DBUILD_FOR_GLFW=${{ matrix.engine-backend == 'glfw' }}
          -DBUILD_FOR_OPENXR=${{ matrix.engine-backend == 'openxr' }}
          -DBUILD_FOR_LINUX=${{ matrix.operating-system == 'linux' }}
          -DBUILD_FOR_MACOS=${{ matrix.operating-system == 'macos' }}
          -DBUILD_FOR_WINDOWS=${{ matrix.operating-system == 'windows' }}
          -DBUILD_SHARED_LIBS=OFF
          -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: >
          cmake
          --build ${{ github.workspace }}/build
          --config Release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ github.workspace }}/${{ matrix.target }}.bin
          generate_release_notes: true

  release-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6.0.2

      - name: Setup JDK
        uses: actions/setup-java@v5.2.0
        with:
          distribution: "temurin"
          java-version: ${{ env.JAVA_TUMERIN_JDK_VERSION }}

      - name: Setup Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.ANDROID_NDK_VERSION }}

      - name: Build APK
        working-directory: ${{ github.workspace }}/platforms/openxr/android
        run: ./gradlew assembleRelease

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ github.workspace }}/platforms/openxr/android/app/build/outputs/apk/release/app-release.apk
          generate_release_notes: true
